global using AutoMapper;
global using BLL.App.Services;
global using BLL.Base;
global using Contracts.BLL.App;
global using Contracts.BLL.App.Services;
global using Contracts.DAL.App;
global using BLL.App.Mappers;
global using BLL.Base.Services;
global using Contracts.DAL.App.Repositories;
global using BLLAppDTO = BLL.App.DTO;
global using DALAppDTO = DAL.App.DTO;
global using Contracts.BLL.Base.Mappers;